'''

For two strings with the same length, count every single time the two characters are different

'''

def haystack (a,b):
    answers = []
    lengthOfA = len(a)
    startOfB = 0
    lengthOfB = len(b)

    diffOfLength = lengthOfA - lengthOfB + 1
    for i in range(0,diffOfLength):
        if a[i : lengthOfB] == b:
            answers.append((i + 1))
        lengthOfB += 1
    return answers

answers = haystack("AGGGCCAAAGGGCCACATCAAGGGCCACAGGGCCAGCCCGAAGCTGCTAACCCAGGGCCATCGAAAGGGCCAAGGGCCAAGGGCCAGATAGGGCCAACGCGAGGGCCACGGCAGGGCCACCCATCTTAGGGCCATAGGGCCATGTCAGGGCCATCTGAGGGCCACGCTAGGGCCACCTCTGAAAATATGCGGTAGGGCCACGCAGGGCCATTTAGGGCCAACGTGACAGGGCCAAGGGCCAGAGGGCCAAGTAGGGCCACTTAAAGGGCCACTGAGCGAGAGGGCCATCAGGGCCATGCACGAGGGCCAAAGGGCCACTAGTTAGAGAAGGGCCAGAGGGCCAAGGGCCAAGGGCCACTATTCCTGCTTTACGTGAGGGCCAGAGGGCCATAGGGCCAAGGGCCAATTAGGGCCAAGGGCCACTTTAGGGCCAGGCGAAGGGCCACCAGGGCCACGAAGGGCCAGGTAGGGCCACGATGAGATCGGGCAGGGCCAAATTCAAGGAGGAAGGGCCATTTTAGGGCCAATAAGGGCCAATCATGTAGGGCCACAAAGGGCCATACAGGGCCACAGGGCCAGGAGGGCCAAGGGCCACGTCTAGGGCCAAGGGCCACTCCACTGCAGGGCCAAGGGCCAATTAGGGCCAGTCTTCAGTTAGGGCCAAGGGCCAAAAAGGGCCAAGGGCCAACAGGGCCACTTAAGGGCCAAGGGCCACGTTAGGGCCAGGTACAGGGCCAATCCAGGGCCACAGGGCCAAGGGCCAAGGGCCAAGAAAGGGCCACAGGGCCATAGGGCCATAAGCAGAGGGCCAAGGGCCAAGGGCCA", "AGGGCCAAG")

count = 0
output = ''
for i in answers:
    output += str(i)
    output += " "

print(output)